server:
  port: 8080
  servlet:
    contextPath: /v1

spring:
  jpa:
    show-sql: true
    open-in-view: false
    h2:
      console:
        enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: password
